### PR TITLE
OEL-3691: Fixed routed issue and added test.

### LINKED ISSUE #464: PHP error when using external url in menu after updating to 1.20.0.
Due to a change in version 1.20.0, after updating the theme, the following error is breaking the site when there is an external URL in the menu:

```
UnexpectedValueException: https://example.com has no corresponding route. in Drupal\Core\Url->getRouteName() (line 567 of core/lib/Drupal/Core/Url.php).

Drupal\oe_bootstrap_theme\MenuPreprocess->menuLink(Array) (Line: 39)
Drupal\oe_bootstrap_theme\MenuPreprocess->preprocessMenu(Array, 'menu__main') (Line: 18)
oe_bootstrap_theme_preprocess_menu(Array, 'menu__main', Array)
call_user_func_array('oe_bootstrap_theme_preprocess_menu', Array) (Line: 261)
Drupal\Core\Theme\ThemeManager->render('menu__main', Array) (Line: 491)
...
```
The issue is that it's not checked if Url is routed or not before calling `getRouteName()` here:
https://github.com/openeuropa/oe_bootstrap_theme/blob/1.20.0/src/MenuPreprocess.php#L166

We are applying the following patch to fix it for now:

```diff
diff --git a/src/MenuPreprocess.php b/src/MenuPreprocess.php
index bed51ccc..97a27f66 100644
--- a/src/MenuPreprocess.php
+++ b/src/MenuPreprocess.php
@@ -6,6 +6,7 @@

 use Drupal\Core\Access\AccessResultInterface;
 use Drupal\Core\Template\Attribute;
+use Drupal\Core\Url;

 /**
  * Class containing menu theme and preprocesses.
@@ -160,11 +161,15 @@ public function addDropbuttonClasses(array &$links): void {
    *   The altered menu link.
    */
   public function menuLink(array $menu_link, array $extra_classes = []): array {
-    $link = $menu_link + [
-      'label' => $menu_link['title'],
+    $path = $menu_link['url'];
+    if ($path instanceof Url && $path->isRouted() && $path->getRouteName() === '<nolink>' && !empty($menu_link['below'])) {
       // Setting path to # for dropdown trigger to be rendered as anchor tags.
-      'path' => ($menu_link['url']->getRouteName() === '<nolink>' && !empty($menu_link['below'])) ? '#' : $menu_link['url'],
-    ];
+      $path = '#';
+    }
+    $link = $menu_link + [
+        'label' => $menu_link['title'],
+        'path' => $path,
+      ];

     $attributes = [];
     if (!empty($menu_link['attributes'])) {
```

### PR DESCRIPTION
**Pull request by tibi2303**
Jira issue(s):
- [D8AGE-???](https://webgate.ec.europa.eu/CITnet/jira/browse/D8AGE-???)

### CODE REVIEW

File: tests/src/Kernel/MenuPreprocessTest.php [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+    'system',
+    'user',
+  ];
+
+  /**
+   * The MenuPreprocess service under test.
+   *
+   * @var \Drupal\oe_bootstrap_theme\MenuPreprocess
+   */
+  protected MenuPreprocess $preprocess;
```
Comment (drishu) [inline tests/src/Kernel/MenuPreprocessTest.php]: no need

File: tests/src/Kernel/MenuPreprocessTest.php [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+
+    $result = $this->preprocess->menuLink($menu_link);
+
+    $this->assertSame($url, $result['path']);
+  }
+
+  /**
+   * Tests that external (non-routed) URLs do not trigger getRouteName().
+   */
+  public function testMenuLinkWithExternalUrl(): void {
```
Comment (drishu) [inline tests/src/Kernel/MenuPreprocessTest.php]: Lets merge all these into one test with a provider

File: tests/src/Kernel/MenuPreprocessTest.php [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+      'below' => [
+        ['title' => 'Child item', 'url' => Url::fromRoute('<front>')],
+      ],
+    ];
+
+    $result = $this->preprocess->menuLink($menu_link);
+
+    $this->assertSame($url, $result['path']);
+  }
+
```
Comment (drishu) [inline tests/src/Kernel/MenuPreprocessTest.php:364]: if we add a dedicated test for the class lets cover the other methods aswell

File: tests/src/Kernel/MenuPreprocessTest.php [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+namespace Drupal\Tests\oe_bootstrap_theme\Kernel;
+
+use Drupal\Core\Template\Attribute;
+use Drupal\Core\Url;
+use Drupal\oe_bootstrap_theme\MenuPreprocess;
+use Drupal\KernelTests\KernelTestBase;
+
+/**
+ * Tests the MenuPreprocess service logic.
+ */
```
Comment (drishu) [inline tests/src/Kernel/MenuPreprocessTest.php:19]: please add a 'covers' so php coverage tools are aware

**Review by drishu — CHANGES_REQUESTED** [review]
the fix is ok, the test needs a bit of work

File: tests/src/Kernel/MenuPreprocessTest.php [hunk 5]
```diff
@@ -0,0 +1,329 @@
...
+
+    $preprocess->preprocessMenu($variables, 'menu__main');
+    $this->assertCount(2, $variables['items']);
+
+    $item1 = $variables['items'][0];
+    $this->assertArrayHasKey('standalone', $item1);
+    $this->assertTrue($item1['standalone']);
+    $this->assertTrue($item1['dropdown']);
+    $this->assertTrue($item1['link']);
+    $this->assertArrayHasKey('trigger', $item1);
```
Comment (drishu) [inline tests/src/Kernel/MenuPreprocessTest.php:172]: assert the parent is correct, not just present

File: tests/src/Kernel/MenuPreprocessTest.php [hunk 6]
```diff
@@ -0,0 +1,329 @@
...
+    $this->assertArrayHasKey('items', $item1);
+    $this->assertCount(2, $item1['items']);
```
Comment (drishu) [inline tests/src/Kernel/MenuPreprocessTest.php:180]: assert the urls of the items and children

File: tests/src/Kernel/MenuPreprocessTest.php [hunk 7]
```diff
@@ -0,0 +1,329 @@
...
+  /**
+   * Tests MenuPreprocess::preprocessMenu().
+   */
+  public function testPreprocessMenu(): void {
+    $preprocess = new MenuPreprocess();
+
+    $variables = [
+      'items' => [
+        [
+          'title' => 'Parent 1',
```
Comment (drishu) [inline tests/src/Kernel/MenuPreprocessTest.php:139]: add also one with in_active_trail

File: tests/src/Kernel/MenuPreprocessTest.php [hunk 8]
```diff
@@ -0,0 +1,329 @@
...
+          'link' => [
+            '#url' => Url::fromRoute('<front>'),
+            '#options' => [
+              'attributes' => [
+                'class' => [],
+              ],
+            ],
+          ],
+        ],
+      ],
```
Comment (drishu) [inline tests/src/Kernel/MenuPreprocessTest.php:230]: add a <nolink>

File: tests/src/Kernel/MenuPreprocessTest.php [hunk 9]
```diff
@@ -0,0 +1,329 @@
...
+      'secondary' => [],
+    ];
+
+    $preprocess->preprocessMenuLocalTasks($variables);
+
+    $this->assertCount(2, $variables['primary']);
+    $this->assertEquals('Active Task', $variables['primary'][0]['label']);
+    $this->assertEquals('Some Task', $variables['primary'][1]['label']);
+
+    $this->assertTrue($variables['primary'][0]['attributes']->hasClass('active'),);
```
Comment (drishu) [inline tests/src/Kernel/MenuPreprocessTest.php]:
```suggestion
    $this->assertTrue($variables['primary'][0]['attributes']->hasClass('active'));
```

**Review by drishu — CHANGES_REQUESTED** [review]

File: tests/src/Kernel/MenuPreprocessTest.php (hunk 5 above)
Comment (tibi2303) [reply tests/src/Kernel/MenuPreprocessTest.php:172]: i added more asserts here

File: tests/src/Kernel/MenuPreprocessTest.php (hunk 6 above)
Comment (tibi2303) [reply tests/src/Kernel/MenuPreprocessTest.php:180]: testing that too

File: tests/src/Kernel/MenuPreprocessTest.php (hunk 7 above)
Comment (tibi2303) [reply tests/src/Kernel/MenuPreprocessTest.php:139]: added

File: tests/src/Kernel/MenuPreprocessTest.php (hunk 9 above)
Comment (tibi2303) [reply tests/src/Kernel/MenuPreprocessTest.php]: done

**Review by drishu — APPROVED** [review]
